'use strict';
const $ = id => document.getElementById(id);
const state = {status:null,jobs:[],activeId:null,submitting:false,loginId:null,jobsLoading:false,statusLoading:false,historySignature:'',actionSignature:'',approvalSignature:'',eventSignature:'',videoUrl:null,toastTimer:null};
const activeStates = new Set(['queued','running','waiting_approval']);
const labels = {queued:'Queued',running:'In production',completed:'Ready to watch',failed:'Needs attention',cancelled:'Stopped',interrupted:'Paused',waiting_approval:'Needs your review'};
const stages = ['Story','Cast & assets','Audio','Animation','Final edit'];
const modeLabels = {codex:'Codex production',demo:'Local demo'};
function message(error){return error instanceof Error?error.message:String(error||'Something went wrong. Please try again.');}
function showError(id,value){$(id).textContent=value||'';$(id).hidden=!value;}
function toast(value){clearTimeout(state.toastTimer);$('toast').textContent=value;$('toast').hidden=false;state.toastTimer=setTimeout(()=>{$('toast').hidden=true;},5000);}
function available(value){return value===true||Boolean(value&&typeof value==='object'&&(value.available===true||value.installed===true));}
function safeUrl(value){if(!value||typeof value!=='string')return null;try{const url=new URL(value,location.origin);return url.origin===location.origin&&['http:','https:'].includes(url.protocol)?url.href:null;}catch{return null;}}
async function api(path,options={}){
 const config={credentials:'same-origin',cache:'no-store',...options};
 if(config.method&&config.method!=='GET'){if(!state.status?.csrf_token)throw new Error('The studio is not connected yet. Wait a moment and try again.');config.headers={'Content-Type':'application/json','X-Studio-Token':state.status.csrf_token,...config.headers};config.body=JSON.stringify(config.body||{});}
 const response=await fetch(path,config);let result;try{result=await response.json();}catch{throw new Error('The studio returned an unreadable response. Check that the local server is running.');}
 if(!response.ok){const detail=result?.error||result?.detail||result?.message;throw new Error(typeof detail==='string'?detail:`The request could not be completed (${response.status}).`);}return result;
}
function codexReady(){const c=state.status?.codex;return Boolean(c?.connected&&['chatgpt','chatgptAuthTokens'].includes(c.auth_mode));}
function controls(){const ready=Boolean(state.status?.csrf_token);$('generate-button').disabled=!ready||state.submitting;$('generate-label').textContent=state.submitting?'Starting your production…':'Create with Codex';$('demo-button').disabled=!ready||state.submitting;const codex=state.status?.codex||{};$('codex-login').disabled=!ready||!codex.available||Boolean(state.loginId)||codexReady();$('codex-login').hidden=codexReady();}
function connection(online){$('connection-status').className=`connection-status ${online?'online':'offline'}`;const dot=document.createElement('span');dot.className='status-dot';$('connection-status').replaceChildren(dot,document.createTextNode(online?'Local studio connected':'Studio disconnected'));}
function updateStatus(result){
 state.status=result;connection(true);if(result.output_dir)$('output-location').textContent=`Output folder: ${result.output_dir}`;
 const codex=result.codex||{};
 if(state.loginId&&codex.login_pending===false&&!codexReady()){state.loginId=null;$('login-actions').hidden=true;if(codex.error)showError('submit-error',String(codex.error));}
 if(codexReady()){$('codex-status').textContent=`Codex is connected${codex.plan?` · ${String(codex.plan)}`:''}`;$('codex-badge').textContent='CONNECTED';$('codex-badge').classList.add('connected');if(state.loginId)toast('Codex is connected. Your studio is ready.');state.loginId=null;$('login-actions').hidden=true;}
 else{$('codex-status').textContent=state.loginId?'Finish signing in in the new tab…':codex.available?(codex.connected?'Sign in with ChatGPT to use your Codex plan':'Sign in to connect your creative agent'):'Codex is not installed yet';$('codex-badge').textContent='CODEX';$('codex-badge').classList.remove('connected');}
 const caps=result.capabilities||{};const missing=[];if(!available(caps.blender))missing.push('Blender');if(!available(caps.ffmpeg))missing.push('FFmpeg');
 $('blender-note').textContent=missing.length?`Your agent can help set up ${missing.join(' and ')} before production.`:'Your local animation and editing tools are ready.';
 if(codex.error&&!codex.connected&&!state.loginId)$('codex-status').textContent=String(codex.error);controls();
}
async function loadStatus(){if(state.statusLoading)return;state.statusLoading=true;try{updateStatus(await api('/api/status'));showError('global-alert','');}catch{state.status=null;connection(false);showError('global-alert','Cannot reach the local studio. Keep the launcher running, then refresh this page.');controls();}finally{state.statusLoading=false;}}
function promptCount(){$('prompt-count').textContent=`${$('prompt').value.length.toLocaleString()} / 12,000`;}
async function submit(provider){
 if(state.submitting)return;showError('submit-error','');const prompt=provider==='demo'?'A friendly character waves hello in a sunny courtyard. A local Blender pipeline demo.':$('prompt').value.trim();
 if(provider==='codex'&&prompt.length<12){showError('submit-error','Describe your story with a little detail: a character, an action, and a setting.');$('prompt').focus();return;}
 if(provider==='codex'&&!codexReady()){showError('submit-error','Sign in with ChatGPT above to connect Codex first.');$('codex-fields').scrollIntoView({behavior:'smooth',block:'center'});return;}
 if(provider==='demo'&&(!available(state.status?.capabilities?.blender)||!available(state.status?.capabilities?.ffmpeg))){showError('submit-error','The local demo needs Blender and FFmpeg. Connect Codex to help set up your production tools.');return;}
 state.submitting=true;controls();
 const payload={provider,prompt,duration:provider==='demo'?8:Number($('duration').value),aspect:$('aspect').value,style:$('style').value,quality:$('quality').value,narration:$('narration').checked,captions:$('captions').checked,music:$('music').checked};
 try{const result=await api('/api/jobs',{method:'POST',body:payload});const job=result.job||result;state.activeId=job.id;state.jobs=[job,...state.jobs.filter(item=>item.id!==job.id)];renderHistory();renderJob(job);toast(provider==='demo'?'Your local demo is underway.':'Your film is in production. Follow each stage in the screening room.');if(matchMedia('(max-width: 970px)').matches)$('job-preview').scrollIntoView({behavior:'smooth',block:'center'});await loadJobs();}
 catch(error){showError('submit-error',message(error));}finally{state.submitting=false;controls();}
}
function chooseJob(job){state.activeId=job.id;state.actionSignature='';state.approvalSignature='';state.eventSignature='';renderJob(job);renderHistory();}
function lengthLabel(value){if(!value)return'';return Number(value)>=60?`${Number(value)/60} min`:`${value}s`;}
function renderHistory(){
 $('library-count').textContent=String(state.jobs.length);const signature=JSON.stringify(state.jobs.map(job=>[job.id,job.title,job.status,job.thumbnail_url,job.duration,job.aspect,job.created_at]))+state.activeId;if(signature===state.historySignature)return;state.historySignature=signature;if(!state.jobs.length)return;
 const list=$('job-list');list.replaceChildren();
 for(const job of state.jobs){const card=document.createElement('button');card.type='button';card.className=`history-card${job.id===state.activeId?' current':''}`;card.setAttribute('aria-label',`Open ${job.title||'Untitled film'}, ${labels[job.status]||job.status}`);card.addEventListener('click',()=>{chooseJob(job);$('job-preview').scrollIntoView({behavior:'smooth',block:'center'});});
 const thumbnail=safeUrl(job.thumbnail_url);if(thumbnail){const img=document.createElement('img');img.className='history-image';img.src=thumbnail;img.alt='';img.loading='lazy';card.append(img);}else{const placeholder=document.createElement('div');placeholder.className='history-placeholder';const icon=document.createElement('span');icon.textContent=job.status==='completed'?'▷':'✧';const label=document.createElement('small');label.textContent=modeLabels[job.provider]||'FILM';placeholder.append(label,icon);card.append(placeholder);}
 const content=document.createElement('div');content.className='history-content';const title=document.createElement('p');title.className='history-title';title.textContent=job.title||job.prompt||'Untitled film';const meta=document.createElement('div');meta.className='history-meta';const details=document.createElement('span');const date=new Date(job.created_at);details.textContent=[lengthLabel(job.duration),job.aspect||'',Number.isNaN(date.getTime())?'':date.toLocaleDateString(undefined,{month:'short',day:'numeric'})].filter(Boolean).join(' · ');const badge=document.createElement('span');badge.className=`job-badge ${String(job.status||'').replace(/[^a-z_-]/g,'')}`;badge.textContent=labels[job.status]||job.status||'Unknown';meta.append(details,badge);content.append(title,meta);card.append(content);list.append(card);}
}
function fileLink(label,url,secondary=false,download=false){const safe=safeUrl(url);if(!safe)return null;const link=document.createElement('a');link.className=`job-action${secondary?' secondary':''}`;link.textContent=label;link.href=safe;if(download)link.download='';else{link.target='_blank';link.rel='noopener noreferrer';}return link;}
function addLink(container,label,url,secondary=false,download=false){const link=fileLink(label,url,secondary,download);if(link)container.append(link);}
async function updateJobAction(button,job,action){button.disabled=true;try{const result=await api(`/api/jobs/${encodeURIComponent(job.id)}/${action}`,{method:'POST',body:{}});const updated=result.job||result;if(updated.id){state.jobs=state.jobs.map(item=>item.id===job.id?updated:item);renderJob(updated);}await loadJobs();toast(action==='resume'?'Production is continuing from the saved project.':'Production stopped. Your saved work is still available.');}catch(error){showError('job-error',message(error));button.disabled=false;}}
function renderActions(job){const signature=JSON.stringify([job.id,job.status,job.video_url,job.project_url,job.plan_url,job.package_url,job.captions_url,job.script_url,job.credits_url,job.can_resume]);if(signature===state.actionSignature)return;state.actionSignature=signature;const actions=$('job-actions');actions.replaceChildren();
 if(job.status==='completed'&&job.video_url)addLink(actions,'Download film ↓',job.video_url,false,true);if(job.project_url)addLink(actions,String(job.project_url).endsWith('.zip')?'Production files ↓':'Blender project ↓',job.project_url,true,true);else if(job.package_url)addLink(actions,'Production files ↓',job.package_url,true,true);if(job.script_url)addLink(actions,'Story script ↓',job.script_url,true,true);if(job.captions_url)addLink(actions,'Captions ↓',job.captions_url,true,true);if(job.credits_url)addLink(actions,'Credits ↓',job.credits_url,true,true);if(job.plan_url)addLink(actions,'Scene plan ↓',job.plan_url,true,true);
 if(activeStates.has(job.status)){const stop=document.createElement('button');stop.type='button';stop.className='job-action secondary';stop.textContent='Stop production';stop.addEventListener('click',()=>updateJobAction(stop,job,'cancel'));actions.append(stop);}
 if(job.can_resume&&!activeStates.has(job.status)&&job.status!=='completed'){const resume=document.createElement('button');resume.type='button';resume.className='job-action';resume.textContent='Continue production →';resume.addEventListener('click',()=>updateJobAction(resume,job,'resume'));actions.append(resume);}
}
function renderApprovals(job){const pending=Array.isArray(job.approvals)?job.approvals.filter(item=>!item.status||item.status==='pending'):[];const signature=JSON.stringify(pending);if(signature===state.approvalSignature)return;state.approvalSignature=signature;const list=$('approval-list');list.replaceChildren();
 for(const approval of pending){const card=document.createElement('section');card.className='approval-card';const title=document.createElement('h3');title.textContent=approval.title||'Your agent needs approval';const reason=document.createElement('p');reason.textContent=approval.reason||'Review this action before your agent continues.';card.append(title,reason);if(approval.command){const command=document.createElement('pre');command.textContent=Array.isArray(approval.command)?approval.command.join(' '):String(approval.command);card.append(command);}for(const [label,value] of [['Working folder',approval.cwd],['Requested permissions',approval.permissions],['Files to change',approval.files],['File changes',approval.changes],['Network access',approval.network_context],['Permission duration',approval.scope],['Additional folder access',approval.grant_root]]){if(value){const heading=document.createElement('p');heading.className='approval-detail-label';heading.textContent=label;const detail=document.createElement('pre');detail.textContent=Array.isArray(value)?value.join('\n'):typeof value==='object'?JSON.stringify(value,null,2):String(value);card.append(heading,detail);}}const reviewable=approval.reviewable===true&&approval.details_truncated!==true;if(!reviewable){const warning=document.createElement('p');warning.className='approval-warning';warning.textContent='The full action details are unavailable or need a narrower scope. Approval is disabled. Decline so Codex can propose an action you can fully review.';card.append(warning);}const buttons=document.createElement('div');buttons.className='approval-buttons';for(const approved of[true,false]){const button=document.createElement('button');button.type='button';button.textContent=approved?'Approve action':'Decline';button.dataset.approvalChoice=String(approved);button.disabled=approved&&!reviewable;button.addEventListener('click',async()=>{buttons.querySelectorAll('button').forEach(b=>{b.disabled=true;});try{await api(`/api/approvals/${encodeURIComponent(approval.id)}`,{method:'POST',body:{approved}});toast(approved?'Action approved. Production can continue.':'Action declined. Your agent will receive your decision.');await loadJobs();}catch(error){showError('job-error',message(error));buttons.querySelectorAll('button').forEach(b=>{b.disabled=b.dataset.approvalChoice==='true'&&!reviewable;});}});buttons.append(button);}card.append(buttons);list.append(card);}
}
function renderEvents(job){const events=Array.isArray(job.events)?job.events:[];const signature=JSON.stringify(events);if(signature===state.eventSignature)return;state.eventSignature=signature;$('activity-panel').hidden=!events.length;$('activity-count').textContent=events.length?`(${events.length})`:'';const list=$('activity-list');list.replaceChildren();for(const event of events.slice(-60).reverse()){const item=document.createElement('li');const date=new Date(event.time||event.created_at);if(!Number.isNaN(date.getTime())){const time=document.createElement('time');time.textContent=date.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});time.dateTime=date.toISOString();item.append(time);}item.append(document.createTextNode(String(event.text||event.message||event.type||'')));list.append(item);}}
function stageIndex(job){const stage=String(job.stage||'').toLowerCase();if(/assembl|edit|final|encod|deliver|verif|complete/.test(stage))return 4;if(/render|animat|scene/.test(stage))return 3;if(/audio|voice|sound/.test(stage))return 2;if(/asset|cast|character|model/.test(stage))return 1;if(/plan|story|script|setup/.test(stage))return 0;return Math.min(4,Math.floor((Number(job.progress)||0)/21));}
function renderStages(job){let list=$('production-stages');if(!list){list=document.createElement('div');list.id='production-stages';list.className='stage-list';$('job-message').after(list);}list.replaceChildren();const current=stageIndex(job);stages.forEach((title,index)=>{const item=document.createElement('span');item.className=`stage-item${index<current?' done':index===current?' current':''}`;item.textContent=title;list.append(item);});}
function renderJob(job){if(!job)return;$('empty-preview').hidden=true;$('job-preview').hidden=false;$('preview-format').textContent=job.aspect||$('aspect').value;const video=safeUrl(job.video_url);const ready=job.status==='completed'&&video;$('job-progress-view').hidden=Boolean(ready);$('video-player').hidden=!ready;
 if(ready&&state.videoUrl!==video){$('video-player').src=video;const poster=safeUrl(job.thumbnail_url);if(poster)$('video-player').poster=poster;else $('video-player').removeAttribute('poster');state.videoUrl=video;}else if(!ready&&state.videoUrl){$('video-player').pause();$('video-player').removeAttribute('src');$('video-player').load();state.videoUrl=null;}
 $('job-title').textContent=job.title||(activeStates.has(job.status)?'Bringing your story to life':'Your film');$('job-stage').textContent=activeStates.has(job.status)?(job.provider==='demo'?'RUNNING THE LOCAL DEMO':String(job.stage||'YOUR FILM IS IN PRODUCTION').replace(/[_-]/g,' ').toUpperCase()):(labels[job.status]||job.status||'FILM').toUpperCase();$('job-message').textContent=job.message||(job.status==='queued'?'Your project is queued. This page updates automatically.':'');const progress=Math.max(0,Math.min(100,Number(job.progress)||0));$('progress-fill').style.width=`${progress}%`;$('progress-fill').parentElement.setAttribute('aria-valuenow',String(progress));$('job-percent').textContent=`${Math.round(progress)}%`;$('job-provider').textContent=modeLabels[job.provider]||'FILM';$('progress-orbit').classList.toggle('stopped',!activeStates.has(job.status));showError('job-error',job.error?String(job.error):'');$('cancel-note').hidden=!activeStates.has(job.status);renderStages(job);renderActions(job);renderApprovals(job);renderEvents(job);
}
async function loadJobs(){if(state.jobsLoading)return;state.jobsLoading=true;try{const result=await api('/api/jobs');state.jobs=Array.isArray(result.jobs)?result.jobs:[];if(!state.activeId&&state.jobs.length)state.activeId=state.jobs[0].id;const active=state.jobs.find(job=>job.id===state.activeId);renderHistory();if(active)renderJob(active);}catch{/* The status banner reports lost connections. */}finally{state.jobsLoading=false;}}
async function login(){if(state.loginId||!state.status)return;$('codex-login').disabled=true;showError('submit-error','');let loginWindow=null;try{loginWindow=window.open('about:blank','_blank');if(loginWindow)loginWindow.opener=null;}catch{/* The sign-in link handles blocked popups. */}
 try{const result=await api('/api/codex/login',{method:'POST',body:{}});if(!result.authUrl||!result.loginId)throw new Error('Sign-in could not start. Check that Codex is installed.');const url=new URL(result.authUrl);const official=url.protocol==='https:'&&!url.username&&!url.password&&(url.hostname==='openai.com'||url.hostname.endsWith('.openai.com')||url.hostname==='chatgpt.com'||url.hostname.endsWith('.chatgpt.com'));if(!official)throw new Error('The login endpoint did not return an official OpenAI sign-in URL.');state.loginId=result.loginId;$('login-link').href=url.href;$('login-actions').hidden=false;$('codex-status').textContent='Finish signing in in the new tab…';if(loginWindow&&!loginWindow.closed)loginWindow.location.href=url.href;else toast('Use “Open secure sign-in” to finish connecting Codex.');}
 catch(error){if(loginWindow&&!loginWindow.closed)loginWindow.close();showError('submit-error',message(error));}finally{controls();}}
async function cancelLogin(){if(!state.loginId)return;$('cancel-login').disabled=true;try{await api('/api/codex/cancel',{method:'POST',body:{login_id:state.loginId}});state.loginId=null;$('login-actions').hidden=true;await loadStatus();}catch(error){showError('submit-error',message(error));}finally{$('cancel-login').disabled=false;controls();}}

document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{$('prompt').value=button.dataset.prompt;promptCount();$('prompt').focus();}));
$('prompt').addEventListener('input',promptCount);$('aspect').addEventListener('change',()=>{if(!state.activeId)$('preview-format').textContent=$('aspect').value;});$('video-form').addEventListener('submit',event=>{event.preventDefault();submit('codex');});$('demo-button').addEventListener('click',()=>submit('demo'));$('codex-login').addEventListener('click',login);$('cancel-login').addEventListener('click',cancelLogin);$('refresh-jobs').addEventListener('click',async()=>{$('refresh-jobs').disabled=true;await Promise.all([loadStatus(),loadJobs()]);$('refresh-jobs').disabled=false;});
controls();loadStatus();loadJobs();setInterval(()=>{if(!document.hidden)loadJobs();},2500);setInterval(()=>{if(!document.hidden)loadStatus();},8000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadStatus();loadJobs();}});
